/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.75
 * Generated at: 2022-05-21 10:09:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.store;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/workspace/workspace_hgw_spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/team0/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1651151360745L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0, user-scalable=yes\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://unpkg.com/swiper@7/swiper-bundle.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/storeCommon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/assets/css/storeLayOut.css\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/head.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"wrap\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/nav.jsp", out, false);
      out.write("\r\n");
      out.write("	<div id=\"header\">\r\n");
      out.write("		<div class=\"wrap\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"container\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/category.jsp", out, false);
      out.write("\r\n");
      out.write("		<div id=\"align\">\r\n");
      out.write("			<div class=\"wrap\">\r\n");
      out.write("				<input class=\"search\" placeholder=\"검색어 입력\">\r\n");
      out.write("				<button type=\"button\" id=\"search\">\r\n");
      out.write("					<img src=\"/resources/assets/images/icon_search1.png\" alt=\"검색 버튼\">\r\n");
      out.write("				</button>\r\n");
      out.write("				<div class=\"select\">\r\n");
      out.write("					<select>\r\n");
      out.write("						<option value=\"\" selected>기본순</option>\r\n");
      out.write("						<option value=\"S\">별점 높은순</option>\r\n");
      out.write("						<option value=\"R\">리뷰 많은순</option>\r\n");
      out.write("						<option value=\"D\">배달시간 빠른순</option>\r\n");
      out.write("						<option value=\"M\">최소주문금액 적은순</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"list\">\r\n");
      out.write("			<div class=\"wrap\">\r\n");
      out.write("				<div class=\"list\">\r\n");
      out.write("					<div class=\"desc\">\r\n");
      out.write("						<div class=\"title\">광고 음식점</div>\r\n");
      out.write("						<div class=\"cont\">\r\n");
      out.write("							<ul>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"desc\">\r\n");
      out.write("						<div class=\"title\">일반 음식점</div>\r\n");
      out.write("						<div class=\"cont\">\r\n");
      out.write("							<ul class=\"normal\">\r\n");
      out.write("								<!-- 일반음식점 -->\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function() {\r\n");
      out.write("			var category = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("			var lastNo;\r\n");
      out.write("			var amount;\r\n");
      out.write("			var condition;\r\n");
      out.write("			var search;\r\n");
      out.write("			\r\n");
      out.write("			function getStoreStr(store) {\r\n");
      out.write("				var str = '';\r\n");
      out.write("				var noimage = \"'/resources/assets/images/noimage.png'\";\r\n");
      out.write("	\r\n");
      out.write("				str += '<li data-sno=\"' + store.sno + '\" data-rn=\"' + store.rn + '\"><a href=\"/store/detail/' + store.sno + '\" class=\"inner\">';\r\n");
      out.write("				str += '		<div class=\"img\">';\r\n");
      out.write("				str += '			<img onerror=\"this.src=' + noimage + '\" src=\"/display?uuid=' + store.attach.uuid + '&path=' + store.attach.path + '&origin=' + store.origin + '\">';\r\n");
      out.write("				str += '		</div>';\r\n");
      out.write("				str += '		<div class=\"con\">';\r\n");
      out.write("				str += '			<div class=\"ttl\">' + store.name + '</div>';\r\n");
      out.write("				str += '			<div class=\"txt\">';\r\n");
      out.write("				str += '				<p>★</p>';\r\n");
      out.write("				str += '				<em>' + store.scope + '</em><span>리뷰 ' + store.reviewNum + '</span><span>사장님 댓글 ' + store.replyNum + '</span><span>최소주문금액 ' + store.minPrice + '</span>';\r\n");
      out.write("				str += '			</div>';\r\n");
      out.write("				str += '			<div class=\"time\">평균 ' + store.delTime + '분</div>';\r\n");
      out.write("				str += '		</div>';\r\n");
      out.write("				str += '</a></li>';\r\n");
      out.write("	\r\n");
      out.write("				return str;\r\n");
      out.write("			}\r\n");
      out.write("	\r\n");
      out.write("			// 일반음식점 목록 띄우기\r\n");
      out.write("			function showStoreList(category, lastNo, amount, condition, search) {\r\n");
      out.write("				var param = {category: category, lastNo: lastNo, amount: amount, condition: condition, search:search}\r\n");
      out.write("				scrollService.getStoreList(param, function(result) {\r\n");
      out.write("					var str = '';\r\n");
      out.write("					for(var i in result) {\r\n");
      out.write("						str += getStoreStr(result[i]);\r\n");
      out.write("					}\r\n");
      out.write("					if(!str) {\r\n");
      out.write("						$(\"ul.normal\").html('해당 조건에 맞는 가게가 없습니다.');\r\n");
      out.write("					}\r\n");
      out.write("					else {\r\n");
      out.write("						$(\"ul.normal\").html(str);\r\n");
      out.write("					}\r\n");
      out.write("				}, function(xhr) {\r\n");
      out.write("					console.log(xhr);\r\n");
      out.write("				})\r\n");
      out.write("			}\r\n");
      out.write("			showStoreList(category, lastNo, amount, condition, search);\r\n");
      out.write("	\r\n");
      out.write("			// 무한스크롤 더보기\r\n");
      out.write("			$(document).scroll(function() {\r\n");
      out.write("				var dh = $(document).height();\r\n");
      out.write("				var wh = $(window).height();\r\n");
      out.write("				var wst = $(window).scrollTop();\r\n");
      out.write("				if(dh == wh + wst) {\r\n");
      out.write("					var lastNo = $(\"ul.normal li:last-child\").data(\"rn\");\r\n");
      out.write("					var param = {category:category, lastNo:lastNo, condition:condition, search:search};\r\n");
      out.write("					scrollService.getStoreList(param, function(result) {\r\n");
      out.write("						var str = '';\r\n");
      out.write("						for(var i in result) {\r\n");
      out.write("							str += getStoreStr(result[i]);\r\n");
      out.write("						}\r\n");
      out.write("						$(\"ul.normal\").append(str);\r\n");
      out.write("					})\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("\r\n");
      out.write("			// 검색어로 가게리스트 재정렬\r\n");
      out.write("			$(\"#search\").on(\"click\", function() {\r\n");
      out.write("				condition = \"F\";\r\n");
      out.write("				search = $(this).closest(\".wrap\").find(\".search\").val();\r\n");
      out.write("				showStoreList(category, lastNo, amount, condition, search);\r\n");
      out.write("			})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			// 필터로 가게리스트 재정렬\r\n");
      out.write("			$(\".select\").on(\"change\", function() {\r\n");
      out.write("				condition = $(this).find(\"option:selected\").val();\r\n");
      out.write("				showStoreList(category, lastNo, amount, condition, search);\r\n");
      out.write("			})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/store/list.jsp(53,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/store/list.jsp(53,7) '${ad}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ad}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/store/list.jsp(53,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("a");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("								<li>\r\n");
            out.write("									<a href=\"/store/detail/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.sno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"inner\">\r\n");
            out.write("										<div class=\"img\">\r\n");
            out.write("											<img onerror=\"this.src='/resources/assets/images/noimage.png'\" src=\"/display?uuid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.attach.uuid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&path=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.attach.path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&origin=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.attach.origin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("										</div>\r\n");
            out.write("										<div class=\"con\">\r\n");
            out.write("											<div class=\"ttl\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("											<div class=\"txt\">\r\n");
            out.write("												<p>★</p>\r\n");
            out.write("												<em>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.scope}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</em><span>리뷰 ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.reviewNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span><span>사장님 댓글 ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.replyNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("											</div>\r\n");
            out.write("											<div class=\"time\">평균 ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.delTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("분</div>\r\n");
            out.write("										</div>\r\n");
            out.write("									</a>\r\n");
            out.write("								</li>\r\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
