/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.75
 * Generated at: 2022-05-22 10:25:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cover_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../views/common/head.jsp", out, false);
      out.write("\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/css/demo.css\" />\r\n");
      out.write("	<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:700,300|Prata' rel='stylesheet' type='text/css' />\r\n");
      out.write("	<script type=\"text/javascript\" src=\"/resources/assets/js/modernizr.custom.26887.js\"></script> \r\n");
      out.write("</head>\r\n");
      out.write("	<body class=\"spinPanel\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../views/common/nav.jsp", out, false);
      out.write("\r\n");
      out.write("        <div class=\"containers\">\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"coverHead\">\r\n");
      out.write("				<div class=\"text\">\r\n");
      out.write("					<a href=\"index\"><strong>오늘 뭐 먹조 <span class=\"text-primary\">?</span></strong></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main\">\r\n");
      out.write("				<div class=\"fs-slider\" id=\"fs-slider\">\r\n");
      out.write("					<figure>\r\n");
      out.write("						<img src=\"/resources/assets/images/chicken.jpg\" alt=\"image01\" />\r\n");
      out.write("						<a href=\"/store/list/1\">\r\n");
      out.write("							<figcaption>\r\n");
      out.write("								<h3>치킨</h3>\r\n");
      out.write("								<p> 후라이드치킨, 양념치킨, 파닭, 순살치킨, 오븐구이, 옛날통닭 </p>\r\n");
      out.write("							</figcaption>\r\n");
      out.write("						</a>\r\n");
      out.write("					</figure>\r\n");
      out.write("					<figure>\r\n");
      out.write("						<img src=\"/resources/assets/images/pizza_cover.jpg\" alt=\"image02\" />\r\n");
      out.write("						<a href=\"/store/list/2\">\r\n");
      out.write("							<figcaption>\r\n");
      out.write("								<h3>양식</h3>\r\n");
      out.write("								<p> 파스타, 피자, 필라프, 리조또, 스테이크, 샐러드, 스튜, 와인 </p>\r\n");
      out.write("							</figcaption>\r\n");
      out.write("						</a>\r\n");
      out.write("					</figure>\r\n");
      out.write("					<figure>\r\n");
      out.write("						<img src=\"/resources/assets/images/chinese.jpg\" alt=\"image03\" />\r\n");
      out.write("						<a href=\"/store/list/3\">\r\n");
      out.write("							<figcaption>\r\n");
      out.write("								<h3>중식</h3>\r\n");
      out.write("								<p> 마라탕, 마라샹궈, 꿔바로우, 짜장면, 짬뽕, 탕수육 </p>\r\n");
      out.write("							</figcaption>\r\n");
      out.write("						</a>\r\n");
      out.write("					</figure>\r\n");
      out.write("					<figure>\r\n");
      out.write("						<img src=\"/resources/assets/images/bibimbap.jpg\" alt=\"image04\" />\r\n");
      out.write("						<a href=\"/store/list/4\">\r\n");
      out.write("							<figcaption>\r\n");
      out.write("								<h3>한식</h3>\r\n");
      out.write("								<p> 삼계탕, 김밥, 곱창, 순대국, 닭도리탕, 곱도리탕, 냉면 </p>\r\n");
      out.write("							</figcaption>\r\n");
      out.write("						</a>\r\n");
      out.write("					</figure>\r\n");
      out.write("					<figure>\r\n");
      out.write("						<img src=\"/resources/assets/images/sushi.jpg\" alt=\"image05\" />\r\n");
      out.write("						<a href=\"/store/list/5\">\r\n");
      out.write("							<figcaption>\r\n");
      out.write("								<h3>일식</h3>\r\n");
      out.write("								<p> 초밥, 돈카츠, 돈까스, 우동, 덮밥, 카레, 나베, 오므라이스 </p>\r\n");
      out.write("							</figcaption>\r\n");
      out.write("						</a>\r\n");
      out.write("					</figure>\r\n");
      out.write("					<figure>\r\n");
      out.write("						<img src=\"/resources/assets/images/bossam.jpg\" alt=\"image06\" />\r\n");
      out.write("						<a href=\"/store/list/6\">\r\n");
      out.write("							<figcaption>\r\n");
      out.write("								<h3>족발/보쌈</h3>\r\n");
      out.write("								<p> 미니족발, 양념족발, 냉채족발, 마늘보쌈, 매운보쌈, 막국수 </p>\r\n");
      out.write("							</figcaption>\r\n");
      out.write("						</a>\r\n");
      out.write("					</figure>\r\n");
      out.write("				</div><!-- /fs-slider -->\r\n");
      out.write("			</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("		<script src=\"/resources/assets/js/jquery.imgslider.js\"></script>\r\n");
      out.write("		<script>\r\n");
      out.write("			$(function() {\r\n");
      out.write("				$( '#fs-slider' ).imgslider();\r\n");
      out.write("			});\r\n");
      out.write("		</script>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
